### ISSUE TITLE
Myinfo helper - Singpass id_token not passed as Bearer token

### ISSUE THREAD

**Issue by causztic** [GovTechSG/singpass-myinfo-oidc-helper#16]
From the docs: https://public.cloud.myinfo.gov.sg/myinfo/tuo/myinfo-tuo-specs.html

> It is required to provide the id_token from the SingPass OIDC login process as "Bearer" in the Authorization header
> MyInfo will validate the id_token to verify if there is a valid SingPass login

**Comment by dyihoon90** [comment]
hi are there any issues you're encountering with the current implementation?

**Comment by aelesia** [comment]
Same thoughts. It seems like MyInfo doesn't even bother to validate the access_token, which is a far bigger problem because it allows the server to query anyone's information.

**Comment by aelesia** [comment]
Same thoughts. It seems like MyInfo doesn't even bother to validate the Bearer token, which is a far bigger problem by itself.

**Comment by dyihoon90** [comment]
I believe there are different types of integrations with SP and MyInfo team. So far this library is more relevant for government applications integrating with Singpass and MyInfo. 

I'll close this issue since its been a while and I am not hearing from the OP. I believe it is not an issue with the lib implementation, as @aelesia pointed out. Feel free to open another ticket if you need to. Thanks!
